---
apiVersion: v2
name: media-processor
description: Helm chart for the media-processor watcher and worker (Temporal-based)
type: application
version: 0.1.0-dev
appVersion: 0.0.1-dev
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
